sudo: false

scripts:
    - sudo apt-get install autoconf automake libusb-dev libusb-1.0-0-dev libplist-dev libplist++-dev usbmuxd libtool libimobiledevice-dev
    - ./autogen.sh
    - make
    - dpkg-buildpackage -rfakeroot -us -uc