language: c

script:
    - sudo dpkg -i deb-files/libimobiledevice-dev_1.2.0+dfsg-1trusty8_amd64.deb
    - sudo add-apt-repository ppa:martin-salbaba/ppa+libimobiledevice -y
    - sudo apt-get update
    - sudo apt-get install autoconf automake libusb-dev libusb-1.0-0-dev libplist-dev libplist++-dev usbmuxd libtool libimobiledevice-dev -y
    - ./autogen.sh
    - make
    - dpkg-buildpackage -rfakeroot -us -uc