language: c
sudo: required
dist: trusty

#Evito che travis lanci una compilazione ogni volta che si crea un tag
branches:
  only:
    - master
    - debian-build

env:
    global:
        - GITHUB_USERNAME: maxgalbu
        - GITHUB_REPO: ios-webkit-debug-proxy
        - GITHUB_REPOPATH: ${GITHUB_USERNAME}/${GITHUB_REPO}
        - GITHUB_TAGNAME: latest
        - secure: "cZKjC9WwpG6izxaCnxnVcS7qT1ZOL2YB6JNnQvW3vcskQIHYLjUo0MrzQopb3/MExGE+GkaG6SeDwIQokLu+m2ESSi1SVr1j9fdZcWtjATkd5+mkvu8NlyO4vzTPbmlb6zjiXJ8LAQ8YQA4qBpoU92Y/FRuT2dt4an09+lyRaLE="

script:
    #Newer version of libimobiledevice and dependencies
    - sudo add-apt-repository ppa:martin-salbaba/ppa+libimobiledevice -y
    - sudo apt-get update

    #Tools to build
    - sudo apt-get install autoconf automake libusb-dev libusb-1.0-0-dev libplist-dev libplist++-dev usbmuxd libtool libimobiledevice-dev -y
    - sudo apt-get install debhelper dh-make -y

    #Build
    - ./autogen.sh
    - make
    - dpkg-buildpackage -rfakeroot -us -uc

    - cd ..

    #Download github-release (https://github.com/aktau/github-release)
    - wget "https://github.com/aktau/github-release/releases/download/v0.6.2/linux-amd64-github-release.tar.bz2"
    - tar xvf linux-amd64-github-release.tar.bz2

    #Use it
    - export FILENAME=$(printf '%s\n' * | grep .deb$)
    - bin/linux/amd64/github-release delete --user $GITHUB_USERNAME --repo $GITHUB_REPO --tag $GITHUB_TAGNAME
    - bin/linux/amd64/github-release release --user $GITHUB_USERNAME --repo $GITHUB_REPO --tag $GITHUB_TAGNAME --name "Latest version"
    - bin/linux/amd64/github-release upload --user $GITHUB_USERNAME --repo $GITHUB_REPO --tag $GITHUB_TAGNAME --name "$FILENAME" --file $FILENAME